#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 \
  --username "$POSTGRES_USER" \
  --dbname postgres <<-EOSQL

  CREATE DATABASE db_auth;
  CREATE DATABASE db_user;
  CREATE DATABASE db_interaction;

  GRANT ALL PRIVILEGES ON DATABASE db_auth TO "$POSTGRES_USER";
  GRANT ALL PRIVILEGES ON DATABASE db_user TO "$POSTGRES_USER";
  GRANT ALL PRIVILEGES ON DATABASE db_interaction TO "$POSTGRES_USER";
EOSQL
