server:
  port: 8084
spring:
  application:
    name: interaction
  datasource:
    #url: jdbc:postgresql://matcha-postgres-dev:5432/db_user
    url: jdbc:postgresql://localhost:5433/db_interaction
    username: ${DB_USER:matcha_user}
    password: ${DB_PASSWORD:topsecretpassword}
    driver-class-name: org.postgresql.Driver