services:
  matcha-postgres-dev:
    container_name: "matcha-postgres-dev"
    image: postgres:18-alpine
    env_file: ".env"
    networks:
      - "matcha-network-dev"
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - matcha-db-data-dev:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
  matcha-redis-dev:
    container_name: "matcha-redis-dev"
    image: redis:8.4.0-alpine
    env_file: ".env"
    networks:
      - "matcha-network-dev"
    restart: always
    ports:
      - "6380:6379"

volumes:
  matcha-db-data-dev:
    name: matcha-db-data-dev

networks:
  matcha-network-dev:
    name: matcha-network-dev
    driver: bridge
