server:
  port: 8081
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 15 #Minutes
    cookie:
      name: ${COOKIE_NAME}
      name-refresh: ${COOKIE_REFRESH_NAME}
      http-only: true
      secure: true
      max-age: 15m
      max-age-refresh: 7d
      same-site: Strict