spring.application.name=Authentication Service

spring.datasource.url=jdbc:postgresql://localhost:5433/db_auth
spring.datasource.username=matcha_user
# If you're seeing this: I know you're seeing my password but it's top secret!
spring.datasource.password=topsecretpassword

spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration