server:
  port: 8081

grpc:
  server:
    port: 9091
    address: 0.0.0.0
    security:
      enabled: false

logging:
  level:
    io.grpc: DEBUG
    io.grpc.netty.shaded.io.netty: DEBUG

spring:
  cache:
    type: redis
  data:
    redis:
      host: matcha-redis-dev
      port: 6379

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 15 #Minutes
      expiration-refresh: 7 #Days
    cookie:
      name: ${COOKIE_NAME}
      name-refresh: ${COOKIE_REFRESH_NAME}
      http-only: true
      secure: true
      max-age: 15m
      max-age-refresh: 7d
      same-site: Strict