services:
  matcha-auth-service-dev:
    container_name: matcha-auth-service-dev
    build:
      context: ..
      dockerfile: infrastructure/services/auth-service/Dockerfile
    networks:
      - "matcha-network-dev"
    restart: always
    ports:
      - "8081:8081"
      - "9091:9091"
    env_file:
      - "../backend/auth/.env"

  matcha-gateway-service-dev:
    container_name: matcha-gateway-service-dev
    build:
      context: ..
      dockerfile: infrastructure/services/gateway-service/Dockerfile
    networks:
      - "matcha-network-dev"
    restart: always
    ports:
      - "9090:9090"
    depends_on:
      - matcha-auth-service-dev
    env_file:
      - "../backend/gateway/.env"

  matcha-user-service-dev:
    container_name: matcha-user-service-dev
    build:
      context: ..
      dockerfile: infrastructure/services/user-service/Dockerfile
    networks:
      - "matcha-network-dev"
    restart: always
    ports:
      - "8082:8082"
      - "9093:9093"
    depends_on:
      - matcha-gateway-service-dev
    env_file:
      - "../backend/user/.env"
  matcha-browse-service-dev:
    container_name: matcha-browse-service-dev
    build:
      context: ..
      dockerfile: infrastructure/services/browse-service/Dockerfile
    networks:
      - "matcha-network-dev"
    restart: always
    ports:
      - "8083:8083"
    depends_on:
      - matcha-gateway-service-dev
      - matcha-user-service-dev

networks:
  matcha-network-dev:
    external: true