spring:
  application:
    name: user
  flyway:
    enabled: true
    locations: classpath:db/migration
  kafka:
    #bootstrap-servers: matcha-kafka-dev:9092
    bootstrap-servers: localhost:9098
    consumer:
      group-id: user-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.trusted.packages: "*"
server:
  port: 8082

