spring:
  datasource:
    url: jdbc:postgresql://matcha-postgres-dev:5432/db_user
    #url: jdbc:postgresql://localhost:5433/db_user
    username: ${DB_USER:matcha_user}
    password: ${DB_PASSWORD:topsecretpassword}
    driver-class-name: org.postgresql.Driver
  application:
    name: user
  flyway:
    enabled: true
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: matcha-kafka-dev:9092
    #bootstrap-servers: localhost:9098
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: user-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.trusted.packages: "*"
server:
  port: 8082

security:
  secret-header:
    value: ${SECRET_HEADER:wSmbKmWf5bxWiG3xI2PAzz8o7dvX4F9i9NGVX24NVm6}